baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Cameron Pfiffer"
theme = "hyde"
copyright = "Cameron Pfiffer"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$", ".rds", ".csv"]

[params]
    themeColor = "theme-base-0f"
    intro = true
    AuthorName = "Cameron Pfiffer"
    github = "https://github.com/cpfiffer"
    linkedin = "https://www.linkedin.com/in/cameron-pfiffer-b4196b55/"
    twitter = "https://twitter.com/CameronPfiffer"
    email = "cpfiffer@gmail.com"
    SocialLinks = true
    TwitterUsername = "CameronPfiffer"
    GithubUsername = "cpfiffer"
    description = " \n Programming, finance, writing."
    dateFormat = "Jan 2, 2006"
    copyrightOwner = "Cameron Pfiffer"
    copyrightStartYear = "2017"
    
[author]
  name = "Cameron Pfiffer"
    
[author.social]
  github = "cpfiffer"
  twitter = "CameronPfiffer"

  
[[menu.main]]
  name = "About"
  weight = -70
  identifier = "about"
  url = "/about/index.html"
  
[[menu.main]]
    Name = "Posts"
    Title = "Show list of posts"
    URL = "/post"
