---
title: Public Comment
author: ~
date: '2017-12-13'
slug: public-comment
categories: []
tags: []
Description: ''
---

Thought I'd just leave these here, via [Matt Levine](https://www.bloomberg.com/view/articles/2017-12-13/regulatory-comments-and-ceo-skill).

[Danny Munson](https://www.sec.gov/comments/10-222/10222-274.htm), an 8th grader from a fictional place in Oregon:

>Dear SEC,

>I am a future stock investor, currently in the 8th grade at Aberdeen Middle School in Wetlawn Oregon. I whole heartily approve of the IEX plan to slow down trading.

>Things move too fast in this world and we need to slow it down in every way we can. Take my school for instance. When we stand in line to pay for our lunch, we have two cashiers to pick from. There is Mr. Fields, who was recently fired from a data entry job. I heard he made some creepy comments to one of his female co-workers. But that isn't important. Mr. Fields can work that cash register like nobodies business. Even when twice as long, most kids will get in Mr. Fields line. Me, on the other hand. I prefer to get in Josephine's line. She used to work at the DMV before failing a drug test. I always get in her line. Sure, it takes me much longer, but she will always give me a compliment and ask me about my day.

>In conclusion, IEX should be rewarded for slowing everything down and moving things backward. Cause backwards is awesome

>Thank you for your time. 

Then, several days later, [Emma Hibernia](https://www.sec.gov/comments/10-222/10222-275.htm) (supposedly a kid from the same school) responds to Danny's comment.

>Dear SEC:

>I saw that letter Danny Mulson wrote to you. The Whole School Saw It. You need to know that Danny Mulson NEVER tells you everything he just tells you what HE wants you to know.

>OK Mr. Fields is fast. BUT Mr. Fields also takes 10 cents from everybody he checks out and when you complain about it he just laughs and says it's part of his job and everybody gets paid for their job so he should too. I thought he already got paid? But he said it wasn't enough. And suppose you want TWO milks well the first milk will cost you one price and then he charges MORE for the second one and you say they were all there to start with and the price tag was the same for ALL of them and he just says things change. WHAT CHANGED??

>And Mr. Fields is creepy too just like Danny said but he didn't tell you everything at all. Mr. Fields got the cafeteria manager to make the GIRLS go down one ramp to the registers and the BOYS go down another ramp and the girls ramp is LOWER so instead of looking at us at eye level he gets to look down at us. Do you get what I mean?? So we complained to the cafeteria managers and they said it makes everything BETTER? And even though I begged her NOT TO my mother complained to the school board and they said they would put it on the agenda for like some meeting a gillion years from now after they talked about parking and everybody is already DEAD.

>Very truly yours,

>Emma 

Sometimes the world _is_ a good place.
