---
title: Corporate Debt
author: ''
date: '2017-09-12'
slug: corporate-debt
categories: []
tags: []
Description: ''
---

This strikes me as [a strange use of corporate cash](https://www.ft.com/content/46027dd2-8f6c-11e7-9084-d0c17942ba93).

>Thirty US companies together have more than $800bn of fixed-income investments, according to a Financial Times analysis of their most recent filings with the US Securities and Exchange Commission.

That's a lot of money. You might be wondering who those thirty companies are, and it's probably who you'd expect -- tech companies with far too much cash sitting around collecting dust. Apple, Alphabet, and Microsoft are cited. 

This strikes me as a huge problem ([I'm not the only one](https://www.economist.com/news/business-and-finance/21722809-their-excuses-doing-so-dont-add-up-tech-firms-hoard-huge-cash-piles)): fixed income investing is really useful if you're trying to meet fixed obligations, like an insurer or pension fund might, or for hedges on inflation and foreign exchange. It's certainly not something research and development companies should be doing. They should be piling that cash into R&D, acquisitions, buybacks, literally anything other than fixed income investments.

I'd also be more than willing to take it. You know, for the team.

We'll close on this happy note:

>The emergence of US companies as a leading investor in corporate debt alongside traditional asset managers comes at a time many in the market express concern about a bond market bubble that could be vulnerable to bursting should inflation and economic growth accelerate.

